// generated by Fast Light User Interface Designer (fluid) version 1.0110

#ifndef genmeta_h
#define genmeta_h

#include <FL/Fl.H>
#include <FL/Fl_File_Chooser.H>
#include <FL/Fl_RGB_Image.H>
#include <FL/fl_draw.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Toggle_Button.H>
#include <FL/Fl_Browser.H>
extern Fl_Browser *spritelist;
#include <FL/Fl_Box.H>
#include <FL/Fl_Menu_Bar.H>
extern Fl_Menu_Item menu_[];

class genmeta: public Fl_Widget {
private:
public:
	genmeta(int x, int y, int w, int h): Fl_Widget(x, y, w, h) {}

	int handle(int e);
	void draw();
};
extern genmeta *meta;

#endif
